### ISSUE TITLE
Linking Librairie

### ISSUE THREAD

**Issue by Morgadegit** [t0mm4rx/ftprintfdestructor#3]
Salut !

Je lance le .sh, ça compile en utilisant mon makefile, ça crée bien ma librairie libprintf.a avec ft_printf dedans, mais juste après ça me dit 
>Generating mains of 1000 tests (1/20)
>ld: library not found for -lftprintf
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>ld: library not found for -lftprintf
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>/bin/sh: ./tests_ftprintf: No such file or directory
>/bin/sh: ./tests_printf: No such file or directory

Le problème vient sûrement de mon côté mais je ne vois pas ce qu'il est ?

Merci d'avance pour ton aide !

**Comment by t0mm4rx** [comment]
Hello !
Le binaire doit s'appeler libftprint.a

**Comment by t0mm4rx** [comment]
@Morgadegit Est-ce que ca fonctionne maintenant ? Peut-tu lock l'issue si c'etait ca ? Merci :)

**Comment by Morgadegit** [comment]
Oui, ça fonctionne une fois le nom changé, merci !
